### ISSUE TITLE
A valid CURL install wasn't found. Install CURL first

### ISSUE THREAD

**Issue by scardario** [mchaptel/ExtensionStore#36]
Hi, trying to run the extension store from Harmony20 on Win10.

it tries to run and then, if I understood correctly the system log, cycles through all the curl.exe(s) found in the system and try to connect to github with the command "-s -S -k https://github.com/", it fails and logs "Couldn't establish a connexion.
Check that somePathInTheSystem/curl.exe has internet access"

I already checked and curl.exe has internet access, it downloads the source for wikipedia.org and google.com. But it does nothing with github.com. (checked with curl.exe located inside Harmony folder in bin_3rdParty)

Maybe it is because I have my github account configured with an SSH key? I have no experience with curl so I have no idea what could be the problem.

Thank you!

![image](https://user-images.githubusercontent.com/12205604/126891720-57a4d753-ef49-4b15-bb5a-facef28ee8da.png)

**Comment by mchaptel** [comment]
Hello, 

Is it possible for you to use another curl.exe than the one bundled with toonboom? Do they all fail that way?
Is github blocked on your domain?

Make sure you test with "https://github.com/" and not "https://www.github.com/".

**Comment by scardario** [comment]
That was the problem, I was testing with www., I tried with several curl on my system (the one in toonboom's folder, in system32, in git folder and the one downloaded directly from curl on my documents folder), and all of them connect to github.com with -s -S -k. HOWEVER, even when it works in command line, it doesn't work from Harmony, it still shows me the same errors:
I can access github without problem from within my browers and it seems to correctly connect with git.

T: 12:28:35.790 Succesfully loaded Extension Store Package.
T: 12:28:36.043 CURL: testing connexion by connecting to github.com
T: 12:28:36.569 CURL: Error: Timeout running command -s -S https://github.com/ (line 367 in file 'C:/Users/scard/AppData/Roaming/Toon Boom Animation/Toon Boom Harmony Premium/2000-scripts/packages/ExtensionStore/lib/network.js')
T: 12:28:36.569 CURL: Couldn't establish a connexion.
Check that C:\WINDOWS/system32/curl.exe has internet access.
T: 12:28:36.569 CURL: testing connexion by connecting to github.com
T: 12:28:37.109 CURL: Error: Timeout running command -s -S https://github.com/ (line 367 in file 'C:/Users/scard/AppData/Roaming/Toon Boom Animation/Toon Boom Harmony Premium/2000-scripts/packages/ExtensionStore/lib/network.js')
T: 12:28:37.109 CURL: Couldn't establish a connexion.
Check that C:\Program Files/Git/mingw64/bin/curl.exe has internet access.
T: 12:28:37.109 CURL: testing connexion by connecting to github.com
T: 12:28:37.635 CURL: Error: Timeout running command -s -S -k https://github.com/ (line 367 in file 'C:/Users/scard/AppData/Roaming/Toon Boom Animation/Toon Boom Harmony Premium/2000-scripts/packages/ExtensionStore/lib/network.js')
T: 12:28:37.635 CURL: Couldn't establish a connexion.
Check that C:/Program Files (x86)/Toon Boom Animation/Toon Boom Harmony 20 Premium/win64/bin/bin_3rdParty/curl.exe has internet access.
T: 12:28:37.635 CURL: A valid CURL install wasn't found. Install CURL first.
T: 12:28:37.635 UI: Error: A valid CURL install wasn't found. Install CURL first. (line 520 in file 'C:/Users/scard/AppData/Roaming/Toon Boom Animation/Toon Boom Harmony Premium/2000-scripts/packages/ExtensionStore/lib/network.js')

**Comment by mchaptel** [comment]
Maybe the timeout used to test the curl binaries is too short for your connexion... Could you edit this line in your local copy and let me know?

https://github.com/mchaptel/ExtensionStore/blob/master/ExtensionStore/lib/network.js#L502

Change the 500 for 3000 or more and see if it works?

**Comment by scardario** [comment]
It worked with 3000 with the first curl found, the one in system32.

Thank you!
